IcicleDefaults = {
    textfont = "Fonts\\FRIZQT__.TTF",
    fontSize = 11,

    all = false,
    arena = true,
    battleground = true,
    field = true,
    party = true,
    raid = true,

    anchorPoint = "BOTTOMLEFT",
    anchorTo = "BOTTOMLEFT",
    xOffset = 0,
    yOffset = -6,

    iconSize = 22,
    iconSpacing = 2,
    maxIconsPerRow = 6,
    maxIcons = 12,
    growthDirection = "RIGHT",
    frameStrata = "LOW",

    showTooltips = true,
    showAmbiguousByName = false,
    showInterruptWhenCapped = true,
    classCategoryFilterEnabled = true,
    showOutOfRangeInspectMessages = true,

    scanInterval = 0.15,
    iconUpdateInterval = 0.10,
    groupScanInterval = 0.35,
    testRefreshInterval = 2.0,

    castMatchWindow = 0.25,
    confHalfLife = 5,
    minConfidence = 0.60,
    mappingTTL = 8,
    minTrackedCooldown = 0,
    maxTrackedCooldown = 0,

    debug = false,
    persistSpecHints = false,
    specDetectEnabled = true,
    specHintTTL = 300,
    inspectRetryInterval = 1.0,
    inspectMaxRetryTime = 30.0,
    defaultEnabledPresetVersion = 0,

    highlightInterrupts = true,
    priorityBorderSize = 1,
    priorityBorderInset = 0,
    priorityBorderPulseIntensity = 1,
    interruptBorderColor = { r = 0.30, g = 0.65, b = 1.00, a = 1.00 },
    itemBorderColor = { r = 1.00, g = 0.82, b = 0.20, a = 1.00 },
    categoryBorderEnabled = {
        GENERAL = true,
        WARRIOR = true,
        PALADIN = true,
        HUNTER = true,
        ROGUE = true,
        PRIEST = true,
        DEATH_KNIGHT = true,
        SHAMAN = true,
        MAGE = true,
        WARLOCK = true,
        DRUID = true,
    },
    categoryBorderColors = {
        GENERAL = { r = 0.62, g = 0.62, b = 0.62, a = 1.00 },
        WARRIOR = { r = 0.78, g = 0.61, b = 0.43, a = 1.00 },
        PALADIN = { r = 0.96, g = 0.55, b = 0.73, a = 1.00 },
        HUNTER = { r = 0.67, g = 0.83, b = 0.45, a = 1.00 },
        ROGUE = { r = 1.00, g = 0.96, b = 0.41, a = 1.00 },
        PRIEST = { r = 1.00, g = 1.00, b = 1.00, a = 1.00 },
        DEATH_KNIGHT = { r = 0.77, g = 0.12, b = 0.23, a = 1.00 },
        SHAMAN = { r = 0.00, g = 0.44, b = 0.87, a = 1.00 },
        MAGE = { r = 0.41, g = 0.80, b = 0.94, a = 1.00 },
        WARLOCK = { r = 0.58, g = 0.51, b = 0.79, a = 1.00 },
        DRUID = { r = 1.00, g = 0.49, b = 0.04, a = 1.00 },
    },

    spellOverrides = {},
    customSpells = {},
    removedBaseSpells = {},
    spellCategories = {},
    disabledSpells = {},
    specHintsByGUID = {},
    specHintsByName = {},
}
