IcicleDefaults = {
    textfont = "Fonts\\FRIZQT__.TTF",
    fontSize = 11,

    all = false,
    arena = true,
    battleground = true,
    field = false,
    party = false,
    raid = false,

    anchorPoint = "BOTTOMLEFT",
    anchorTo = "BOTTOMLEFT",
    xOffset = 0,
    yOffset = -6,

    iconSize = 22,
    iconSpacing = 2,
    maxIconsPerRow = 6,
    maxIcons = 12,
    growthDirection = "RIGHT",
    frameStrata = "LOW",

    showTooltips = false,
    showAmbiguousByName = true,
    showInterruptWhenCapped = true,
    classCategoryFilterEnabled = true,
    showOutOfRangeInspectMessages = true,

    scanInterval = 0.15,
    iconUpdateInterval = 0.10,
    groupScanInterval = 0.35,
    testRefreshInterval = 10.0,

    castMatchWindow = 0.25,
    confHalfLife = 5,
    minConfidence = 0.60,
    mappingTTL = 8,
    minTrackedCooldown = 0,
    maxTrackedCooldown = 0,

    persistSpecHints = false,
    specDetectEnabled = true,
    specHintTTL = 300,
    inspectRetryInterval = 1.0,
    inspectMaxRetryTime = 30.0,
    defaultEnabledPresetVersion = 0,

    highlightInterrupts = true,
    showBorders = false,
    priorityBorderSize = 1,
    priorityBorderInset = 0,
    priorityBorderPulseIntensity = 1,
    interruptBorderColor = { r = 0.30, g = 0.65, b = 1.00, a = 1.00 },
    itemBorderColor = { r = 1.00, g = 0.82, b = 0.20, a = 1.00 },
    categoryBorderEnabled = {
        GENERAL = true,
        WARRIOR = true,
        PALADIN = true,
        HUNTER = true,
        ROGUE = true,
        PRIEST = true,
        DEATH_KNIGHT = true,
        SHAMAN = true,
        MAGE = true,
        WARLOCK = true,
        DRUID = true,
    },
    categoryBorderColors = {
        GENERAL = { r = 0.502, g = 0.502, b = 0.502, a = 1.00 },
        WARRIOR = { r = 0.780, g = 0.612, b = 0.431, a = 1.00 },
        PALADIN = { r = 0.961, g = 0.549, b = 0.729, a = 1.00 },
        HUNTER = { r = 0.671, g = 0.831, b = 0.451, a = 1.00 },
        ROGUE = { r = 1.000, g = 0.961, b = 0.412, a = 1.00 },
        PRIEST = { r = 1.00, g = 1.00, b = 1.00, a = 1.00 },
        DEATH_KNIGHT = { r = 0.769, g = 0.122, b = 0.231, a = 1.00 },
        SHAMAN = { r = 0.000, g = 0.439, b = 0.871, a = 1.00 },
        MAGE = { r = 0.247, g = 0.780, b = 0.922, a = 1.00 },
        WARLOCK = { r = 0.529, g = 0.533, b = 0.933, a = 1.00 },
        DRUID = { r = 1.000, g = 0.490, b = 0.039, a = 1.00 },
    },

    spellOverrides = {},
    customSpells = {},
    removedBaseSpells = {},
    spellCategories = {},
    disabledSpells = {},
    specHintsByGUID = {},
    specHintsByName = {},
}
