IcicleDefaults = {
    textfont = "Fonts\\FRIZQT__.TTF",
    fontSize = 11,

    arena = true,
    battleground = true,
    field = true,
    party = false,
    raid = false,

    anchorPoint = "BOTTOMLEFT",
    anchorTo = "BOTTOMLEFT",
    xOffset = 0,
    yOffset = -6,

    iconSize = 22,
    iconSpacing = 2,
    maxIconsPerRow = 6,
    maxIcons = 12,
    growthDirection = "RIGHT",
    frameStrata = "LOW",

    showTooltips = false,
    showAmbiguousByName = true,
    showInterruptWhenCapped = true,
    classCategoryFilterEnabled = true,
    showOutOfRangeInspectMessages = true,
    debugMode = false,

    scanInterval = 0.15,
    iconUpdateInterval = 0.12,
    groupScanInterval = 0.35,
    testRefreshInterval = 10.0,

    castMatchWindow = 0.25,
    confHalfLife = 5,
    minConfidence = 0.60,
    mappingTTL = 8,
    minTrackedCooldown = 0,
    maxTrackedCooldown = 0,

    persistSpecHints = false,
    specDetectEnabled = true,
    specHintTTL = 300,
    inspectRetryInterval = 1.0,
    inspectMaxRetryTime = 30.0,
    defaultEnabledPresetVersion = 0,

    highlightInterrupts = true,
    interruptHighlightMode = "BORDER",
    showBorders = false,
    priorityBorderSize = 1,
    priorityBorderInset = 0,
    interruptBorderColor = { r = 0.30, g = 0.65, b = 1.00, a = 1.00 },
    itemBorderColor = { r = 1.00, g = 0.82, b = 0.20, a = 1.00 },

    spellOverrides = {},
    customSpells = {},
    removedBaseSpells = {},
    spellCategories = {},
    disabledSpells = {},
    specHintsByGUID = {},
    specHintsByName = {},
}
