IcicleState = IcicleState or {}

function IcicleState.BuildInitialState()
    return {
        knownPlates = {},
        plateMeta = {},
        visiblePlatesByName = {},
        visiblePlateList = {},
        visiblePlateCount = 0,
        visiblePlateIndexByRef = {},
        visibleCount = 0,
        dirtyPlates = {},
        dirtyPlateList = {},
        dirtyPlateCount = 0,

        plateByGUID = {},
        guidByPlate = {},
        candidatesByName = {},
        pendingBindByGUID = {},

        cooldownsByGUID = {},
        cooldownsByName = {},
        recentEventByUnit = {},
        recentUnitSucceededByUnit = {},
        specByGUID = {},
        specByName = {},
        lastSpecAuraCheckByGUID = {},
        classByGUID = {},
        classByName = {},
        reactionByGUID = {},
        reactionByName = {},
        reactionByPlate = {},
        reactionSourceByGUID = {},
        reactionSourceByName = {},
        reactionSourceByPlate = {},
        inspectUnitByGUID = {},
        inspectRequestAtByGUID = {},
        inspectQueue = {},
        inspectQueuedByGUID = {},
        inspectCurrent = nil,
        inspectOutOfRangeSince = {},
        inspectOutOfRangeUnits = {},
        feignDeathAuraByGUID = {},
        lastWorldChildrenCount = 0,
        spellCategoryCache = {},
        expiryHeap = {},
        expiryCount = 0,
        expirySeq = 0,
        scratchRecords = {},
        scratchSpellInfo = {},

        scanAccum = 0,
        iconAccum = 0,
        groupAccum = 0,
        testAccum = 0,
        specAccum = 0,
        inspectAccum = 0,

        testModeActive = false,
        testPool = {},
        testPoolByType = {},
        testByPlate = {},
        ui = {},
    }
end

