IcicleBootstrap = IcicleBootstrap or {}

function IcicleBootstrap.BuildInternalAPI(ctx)
    return {
        GetDB = ctx.GetDB,
        GetState = function() return ctx.STATE end,
        StartCooldown = ctx.StartCooldown,
        ResetAllCooldowns = ctx.ResetAllCooldowns,
        RefreshAllVisiblePlates = ctx.RefreshAllVisiblePlates,
        ResolveUnit = ctx.ResolveUnit,
        ResolveGroupTargets = ctx.ResolveGroupTargets,
        ScanNameplates = ctx.ScanNameplates,
        GetCooldownRule = ctx.GetCooldownRule or ctx.GetSpellConfig,
        GetSpellConfig = ctx.GetSpellConfig,
        DebugSpellRule = ctx.DebugSpellRule,
        SetUnitSpecHint = ctx.SetUnitSpecHint,
        SetPersistSpecHints = ctx.SetPersistSpecHints,
        RunMatrixSelfTests = ctx.RunMatrixSelfTests,
        RunMatrixParityReport = ctx.RunMatrixParityReport,
        RunTriggerParityReport = ctx.RunTriggerParityReport,
        RunRegressionHarness = ctx.RunRegressionHarness,
        RunFullValidation = ctx.RunFullValidation,
        RunDiagnosticReport = ctx.RunDiagnosticReport,
        RunPerformanceReport = ctx.RunPerformanceReport,
        RunReactionMappingReport = ctx.RunReactionMappingReport,
        RunSnapshotFixtureCheck = ctx.RunSnapshotFixtureCheck,
        RunExportConfigPayload = ctx.RunExportConfigPayload,
        RunImportConfigPayload = ctx.RunImportConfigPayload,
        RunExportDefaultDatasetWithNames = ctx.RunExportDefaultDatasetWithNames,
        RunExportShareCode = ctx.RunExportShareCode,
        RunImportShareCode = ctx.RunImportShareCode,
        RunStartupHealthCheck = ctx.RunStartupHealthCheck,
        GetMatrixActionLog = ctx.GetMatrixActionLog,
        ClearMatrixActionLog = ctx.ClearMatrixActionLog,
        BuildSpellRowsData = ctx.BuildSpellRowsData,
        NotifySpellsChanged = ctx.NotifySpellsChanged,
    }
end
